schoolparty/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  namespace :sp_schhools do
    resources :ratings
  end
  match '/users',   to: 'users#index',   via: 'get'
  get '/user', to: redirect('/'), constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  # resources :schools
  # resources :posts
  devise_for :users

  root to: "school_parties#index"
  resources :users
  resources :profiles

  #  devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }


  # devise_for :users

  resources :school_parties
  resources :profiles
  # resources :profiles

  # mount SpAdmission::Engine, :at => "/admission"
  # mount SpSchools::Engine, :at => "/sp_schools"


  # Defines the root path route ("/")

end

schoolparty/app/models/school_party.rb
class SchoolParty < ApplicationRecord
end

schoolparty/app/controllers/school_parties_controller.rb
require "bundler/setup"
require "bunny"
class SchoolPartiesController < ApplicationController
  before_action :set_school_party, only: %i[ show edit update destroy ]


  # Start a communication session with RabbitMQ
  # conn = Bunny.new
  # conn.start
  #
  # # open a channel
  # ch = conn.create_channel
  # ch.confirm_select
  #
  # # declare a queue
  # q  = ch.queue("test1")
  # q.subscribe(manual_ack: true) do |delivery_info, metadata, payload|
  #   puts "This is the message: #{payload}"
  #   # acknowledge the delivery so that RabbitMQ can mark it for deletion
  #   ch.ack(delivery_info.delivery_tag)
  # end
  #
  # # publish a message to the default exchange which then gets routed to this queue
  # q.publish("Hello, everybody!")
  #
  # # await confirmations from RabbitMQ, see
  # # https://www.rabbitmq.com/publishers.html#data-safety for details
  # ch.wait_for_confirms
  #
  # # give the above consumer some time consume the delivery and print out the message
  # sleep 1
  #
  # puts "Done"
  #
  # ch.close
  # # close the connection
  # conn.close
  # GET /school_parties or /school_parties.json
  def index
    @school_parties = SchoolParty.all
  end

  # GET /school_parties/1 or /school_parties/1.json
  def show
  end

  # GET /school_parties/new
  def new
    @school_party = SchoolParty.new
  end

  # GET /school_parties/1/edit
  def edit
  end

  # POST /school_parties or /school_parties.json
  def create
    @school_party = SchoolParty.new(school_party_params)

    respond_to do |format|
      if @school_party.save
        users =  ["ameersohailms@gmail.com", "ameer09981@gmail.com", "varijapatpal056@gmail.com", "varijapatpaljr@gmail.com"]
        conn =  Bunny.new
        conn.start
        ch =  conn.create_channel
        ch.confirm_select
        puts ch.inspect
        q =  ch.queue("test")
        q.subscribe(manual_ack: true) do |delivery_info, meta_data, payload|
          puts "This is the message: #{payload}"
          #   # acknowledge the delivery so that RabbitMQ can mark it for deletion
            ch.ack(delivery_info.delivery_tag)
        end
        q.publish("Hello, everybody!")
        q.publish("Hello1, everybody!")
        q.publish("Hello2, everybody!")
        q.publish("Hello3, everybody!")
        q.publish("Hello4, everybody!")
        # # give the above consumer some time consume the delivery and print out the message
         sleep 1
        puts q.inspect
        puts "Done"
        #
        ch.close
         # close the connection
         conn.close

        # mail(to: "ameersohailms@gmail.com", subject: "You got a new order!")
        # SchoolPartyMailer.with(school_party: @school_party).new_school_party_email.deliver
        puts "ddddddddffffffffffffffffffffffffffffffff"
        # GuestsCleanupJob.perform_later(users)
        puts "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
        format.html { redirect_to school_party_url(@school_party), notice: "School party was successfully created." }
        format.json { render :show, status: :created, location: @school_party }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_parties/1 or /school_parties/1.json
  def update
    respond_to do |format|
      if @school_party.update(school_party_params)
        format.html { redirect_to school_party_url(@school_party), notice: "School party was successfully updated." }
        format.json { render :show, status: :ok, location: @school_party }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_parties/1 or /school_parties/1.json
  def destroy
    @school_party.destroy

    respond_to do |format|
      format.html { redirect_to school_parties_url, notice: "School party was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_party
      @school_party = SchoolParty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_party_params
      params.require(:school_party).permit(:title, :description)
    end
end

schoolparty/app/helpers/school_parties_helper.rb
module SchoolPartiesHelper
end

schoolparty/app/views/school_parties/_form.html.haml
= form_for @school_party do |f|
  - if @school_party.errors.any?
    #error_explanation
      %h2= "#{pluralize(@school_party.errors.count, "error")} prohibited this school_party from being saved:"
      %ul
        - @school_party.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

schoolparty/app/views/school_parties/edit.html.haml
%h1 Editing school_party

= render 'form'

= link_to 'Show', @school_party
\|
= link_to 'Back', school_parties_path

schoolparty/app/views/school_parties/index.html.haml
%h1 SCHOOLS

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Show
      %th Edit
      %th Delete

  %tbody
    - @school_parties.each do |school_party|
      %tr
        %td= school_party.title
        %td= school_party.description
        %td= link_to 'Show', school_party
        %td= link_to 'Edit', edit_school_party_path(school_party)
        %td= link_to 'Destroy', school_party, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New School party', new_school_party_path

schoolparty/app/views/school_parties/new.html.haml
%h1 New school_party

= render 'form'

= link_to 'Back', school_parties_path

schoolparty/app/views/school_parties/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @school_party.title
%p
  %b Description:
  = @school_party.description

= link_to 'Edit', edit_school_party_path(@school_party)
\|
= link_to 'Back', school_parties_path